
name: Compilation test

on:
  push:

jobs:
  run-jpf:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.java }} Run Compilation

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 3e716fcf0a80d91f74cce6545ee089aad1e89ce9

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Compile Java sources
      run: |
        mvn clean install -DskipTests
